# Generated by Django 2.1.5 on 2019-01-22 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('d_id', models.IntegerField(primary_key='true', serialize=False, verbose_name='Dish ID')),
                ('d_name', models.CharField(max_length=20, verbose_name='Dishes name')),
                ('price', models.IntegerField(verbose_name='Prices')),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('Pin', models.IntegerField(primary_key='true', serialize=False, verbose_name='Place ID')),
                ('p_name', models.CharField(max_length=20, verbose_name='Place Name')),
            ],
        ),
        migrations.CreateModel(
            name='Restorent',
            fields=[
                ('r_id', models.IntegerField(primary_key='true', serialize=False, verbose_name='Restorent ID')),
                ('r_name', models.CharField(max_length=20, verbose_name='Restorent name')),
                ('r_place', models.CharField(max_length=20, verbose_name='Place')),
                ('dishes', models.ManyToManyField(to='FoodChain.Dishes')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='p_resto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodChain.Restorent'),
        ),
    ]
